# Generated by Django 5.1.2 on 2024-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ADD_TASK',
        ),
    ]
