# Generated by Django 5.1.2 on 2024-10-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0003_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
